name: Blog Production Deploy

env:
  ECS_WWWROOT_KEY: ${{secrets.ECS_WWWROOT_KEY}}
  SERVER_HOST: ${{secrets.ECS_SERVER_HOST}}
  USER_NAME: ${{secrets.ECS_USER_NAME}}
  SERVER_TARGET: ${{secrets.SERVER_TARGET}}

on:
  push:
    branches:
      - main # default branch

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Generate permalinks
        run: gulp gen-link
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Project Artifacts
        run: npm run build
      - name: Minify
        run: gulp minify
      - name: Deploy
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{env.SERVER_HOST}} >> ~/.ssh/known_hosts
          touch ~/.ssh/id_ecs && echo "${{env.ECS_WWWROOT_KEY}}" > ~/.ssh/id_ecs && chmod 600 ~/.ssh/id_ecs
          eval $(ssh-agent) && ssh-add ~/.ssh/id_ecs && scp -v -r -C public/ ${{env.USER_NAME}}@${{env.SERVER_HOST}}:${{env.SERVER_TARGET}} 
          ssh ${{env.USER_NAME}}@${{env.SERVER_HOST}} "mv -f ${{env.SERVER_TARGET}}/public ${{env.SERVER_TARGET}}/production"

